#数据库驱动mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.5.65.15:3306/blogs?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mKy2*#7btKIuV8CQR(
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#日志打印
logging:
  level:
    root: info
    com.yrp: debug
  file: log/blog-dev.log
server:
  port: 8080
